#!/bin/bash

cd android || return
./gradlew spotlessCheck
result=$?
printf "the spotlessCheck result code is %s." "$result"
if [[ "$result" = 0 ]]; then
  printf "SpotlessCheck Pass!\n"
  ./gradlew detekt
  result=$?
  printf "the DetektCheck result code is %s." "$result"
  if [[ "$result" = 0 ]]; then
    printf "DetektCheck Pass!\n"
  else
    printf "DetektCheck Failed!\n"
    exit 1
  fi
else
  printf "SpotlessCheck Failed!\n"
  exit 1
fi
cd ..
